name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
          should_push: false
          artifact_name: "codebase-visualization"
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "codebase-visualization"
          path: "downloads"